-- TB_TODO 테이블 생성

CREATE TABLE TB_BOOK(
	BOOK_NO 			NUMBER CONSTRAINT TB_BOOK_PK PRIMARY KEY,
	BOOK_TYPE    VARCHAR2(30) NOT NULL,
	BOOK_NAME 		VARCHAR2(4000) NOT NULL,
	BOOK_AUTHOR 	VARCHAR2(60) NOT NULL,
	BOOK_PUBLISHER VARCHAR2(4000) NOT NULL
);


COMMENT ON COLUMN TB_BOOK.BOOK_NO 			IS '도서 번호';
COMMENT ON COLUMN TB_BOOK.BOOK_TYPE  	IS '도서 종류';
COMMENT ON COLUMN TB_BOOK.BOOK_NAME 	IS '책 이름';
COMMENT ON COLUMN TB_BOOK.BOOK_AUTHOR  IS '저자';
COMMENT ON COLUMN TB_BOOK.BOOK_PUBLISHER 			IS '출판사';


-- 샘플 데이터 추가
INSERT INTO TB_BOOK 
VALUES ('895', '문학', '이반 데니소비치의 하루', '알렉산드르 솔제니친', '소담출판사');

INSERT INTO TB_BOOK 
VALUES ('842', '문학', '퍼시 잭슨과 올림포스의 신 1', '릭 라이어던', '한솔수북');

COMMIT;

SELECT * FROM TB_BOOK;

